const BASE = "https://www.premierart.be/assets/img";

export const projects = [
  {
    id: "projet-rue-des-nobles",
    title: "Villa Contemporaine — Rue des Nobles",
    category: "Villa Contemporaine",
    location: "Floreffe, Wallonie",
    year: "2023",
    description:
      "Villa contemporaine implantée sur un terrain en fort dénivelé à Floreffe. Le bâtiment épouse la topographie naturelle : un socle inférieur structure le terrain tandis que le corps de logis principal bénéficie d'une orientation solaire optimale. Bardage bois vertical et enduit clair, menuiseries sombres, piscine prolongeant les espaces intérieurs.",
    fullDescription:
      "L'implantation de cette villa contemporaine, située dans le paysage vallonné de la région de Floreffe, répond aux contraintes spécifiques d'un terrain en fort dénivelé. Le parti pris architectural a consisté à épouser la topographie naturelle plutôt que de la modifier, générant une composition volumétrique où le corps de logis principal en étage repose sur un socle inférieur structurant. Cette gestion fine des niveaux permet d'optimiser l'orientation solaire tout en préservant une échelle discrète depuis l'espace public. La matérialité des façades s'appuie sur une alternance maîtrisée entre un enduit clair et un bardage en bois à pose verticale, une combinaison qui rythme les volumes et adoucit l'orthogonalité de l'édifice tout en favorisant son intégration paysagère. L'organisation spatiale tire pleinement parti du dénivelé pour orienter les plateaux de vie vers le sud et maximiser les dégagements visuels. À l'arrière, le projet affirme une grande perméabilité avec l'extérieur : de généreuses baies vitrées effacent la limite physique entre les espaces de réception et le jardin, faisant de la piscine un véritable prolongement du plan intérieur vers l'extérieur.",
    image: "/projets/rue-des-nobles/0.JPG",
    gallery: [
      "/projets/rue-des-nobles/1.JPG",
      "/projets/rue-des-nobles/2.png",
      "/projets/rue-des-nobles/3.png",
      "/projets/rue-des-nobles/4.JPG",
      "/projets/rue-des-nobles/5.JPG",
      "/projets/rue-des-nobles/6.JPG",
      "/projets/rue-des-nobles/coupe--henin.jpg",
      "/projets/rue-des-nobles/coupe-a--henin.jpg",
      "/projets/rue-des-nobles/etage---henin.jpg",
      "/projets/rue-des-nobles/façade-avant--henin.jpg",
      "/projets/rue-des-nobles/façade-arriere--henin.jpg",
      "/projets/rue-des-nobles/façade-laterale-droite--henin.jpg",
      "/projets/rue-des-nobles/façade-laterale-gauche---henin.jpg",
      "/projets/rue-des-nobles/rdc---henin.jpg",
      "/projets/rue-des-nobles/sous-sol---henin.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: true,
    color: "#2d3a2e",
    displayOrder: 1,
  },
  {
    id: "projet-vollickstraat",
    title: "Rénovation Villa — Vollickstraat",
    category: "Rénovation & Extension",
    location: "Merchtem, Flandre",
    year: "2023",
    description:
      "Transformation lourde d'une villa classique en vaste résidence contemporaine à Merchtem. La surface habitable est doublée — de 300 à 650 m² — par une requalification volumétrique complète. Hall vitré en double hauteur, suite parentale de 90 m², piscine miroir, home-cinéma et salle de sport en sous-sol.",
    fullDescription:
      "Située dans un environnement résidentiel paisible à Merchtem, cette intervention porte sur la transformation lourde d'une villa classique en une vaste résidence contemporaine. Le projet architectural a permis de doubler la surface habitable — passant de 300 à 650 m² — en conservant les qualités structurelles de l'édifice d'origine tout en redéfinissant complètement son expression volumétrique. La façade sur rue affiche une composition orthogonale sobre, rythmée par une généreuse percée vitrée en double hauteur qui signale l'entrée principale et instaure un premier axe de transparence vers l'intérieur. L'organisation spatiale a été repensée pour offrir une fluidité maximale et connecter les différents usages à l'aménagement paysager. Le rez-de-chaussée libère de vastes plateaux de vie systématiquement orientés vers le jardin et la piscine miroir, véritable point d'ancrage visuel du plan. La distribution de l'étage hiérarchise les degrés d'intimité, intégrant de grandes chambres et une suite parentale de 90 m² prolongée par une terrasse privative. En sous-sol, la programmation est complétée par des espaces techniques et de bien-être, incluant une salle de sport et un home-cinema.",
    image: "/projets/vollickstraat/0.png",
    gallery: [
      "/projets/vollickstraat/1.png",
      "/projets/vollickstraat/2.png",
      "/projets/vollickstraat/3.png",
      "/projets/vollickstraat/4.png",
      "/projets/vollickstraat/coupe---coppens.jpg",
      "/projets/vollickstraat/etage---coppens.jpg",
      "/projets/vollickstraat/facade-av---coppens.jpg",
      "/projets/vollickstraat/facade-ar---coppens.jpg",
      "/projets/vollickstraat/facade-l-droite---coppens.jpg",
      "/projets/vollickstraat/facade-l-gauche---coppens.jpg",
      "/projets/vollickstraat/implantation---coppens.jpg",
      "/projets/vollickstraat/rdc---coppens.jpg",
      "/projets/vollickstraat/sous-sol---coppens.jpg",
    ],
    specs: {
      surface: "650 m²",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: true,
    color: "#2a2d35",
    displayOrder: 2,
  },
  {
    id: "projet-emile-bossaert",
    title: "Centre Médical Koekelberg",
    category: "Architecture Médicale",
    location: "Koekelberg, Bruxelles",
    year: "2023",
    description:
      "Reconversion des anciens aquariums de Bruxelles en centre médical pluridisciplinaire de haute technicité. Radiologie, dentisterie, kinésithérapie et bloc opératoire s'organisent autour de patios végétalisés qui injectent la lumière naturelle au cœur du bâtiment.",
    fullDescription:
      "L'aménagement du Centre Médical Koekelberg s'inscrit dans une démarche de réhabilitation lourde, transformant le volume opaque des anciens aquariums de Bruxelles en une infrastructure de santé de haute technicité. Le défi architectural a consisté à inverser la logique d'enfermement initiale pour créer un environnement baigné de lumière naturelle. L'organisation spatiale s'articule autour de percées visuelles stratégiques et de patios végétalisés qui servent de poumons lumineux au bâtiment. Ces dispositifs ne sont pas seulement esthétiques : ils assurent une régulation thermique naturelle et servent de repères intuitifs pour la déambulation des patients au sein d'un programme fonctionnel complexe (radiologie, dentisterie, kinésithérapie et bloc opératoire). Le projet répond rigoureusement aux flux distincts des praticiens et des patients. Les zones d'attente et de circulation privilégient une ergonomie fluide et apaisante, utilisant des matériaux pérennes et des teintes sobres pour réduire le stress lié au cadre médical.",
    image: "/projets/emile-bossaert/0.png",
    gallery: [
      "/projets/emile-bossaert/1.png",
      "/projets/emile-bossaert/2.png",
      "/projets/emile-bossaert/3.png",
      "/projets/emile-bossaert/4.png",
      "/projets/emile-bossaert/5.png",
      "/projets/emile-bossaert/6.png",
      "/projets/emile-bossaert/7.png",
      "/projets/emile-bossaert/coupe---cmk.jpg",
      "/projets/emile-bossaert/coupe-1---cmk.jpg",
      "/projets/emile-bossaert/facade---cmk.jpg",
      "/projets/emile-bossaert/facade-1---cmk.jpg",
      "/projets/emile-bossaert/implantation---cmk.jpg",
      "/projets/emile-bossaert/rdc---cmk.jpg",
      "/projets/emile-bossaert/rdj---cmk.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: true,
    color: "#2a2830",
    displayOrder: 3,
  },
  {
    id: "projet-pierre-van-huffel",
    title: "Immeuble d'Angle — Pierre Van Huffel",
    category: "Immeuble Résidentiel",
    location: "Bruxelles",
    year: "2022",
    description:
      "Immeuble de logements à la croisée de deux axes bruxellois, agissant comme charnière urbaine. Deux duplex familiaux et deux garages. Façade en brique rouge à appareillage texturé, menuiseries beiges, encorbellement marquant la verticalité de l'angle.",
    fullDescription:
      "Cette intervention, développée pour le compte du promoteur Royal City Immo, porte sur l'insertion d'un immeuble de logements à la croisée de deux axes routiers bruxellois. Agissant comme une véritable charnière urbaine, le projet s'intègre avec rigueur dans son contexte mitoyen tout en affirmant une identité architecturale lisible. La volumétrie tire intelligemment parti de la parcelle d'angle, notamment par un jeu d'encorbellement qui accentue la verticalité du bâtiment tout en marquant la transition entre l'artère principale et la rue secondaire. Le programme, compact et optimisé pour la densité urbaine, s'articule autour de deux garages en rez-de-chaussée surmontés de deux duplex familiaux. Initié conceptuellement par le bureau ODM architecture, le projet a été repris par le bureau PREMIER ART qui en a assuré la résolution technique, le suivi de chantier et la réalisation complète. La façade principale se distingue par l'utilisation d'une brique rouge mise en œuvre selon un appareillage texturé, alternant les nuances et les reliefs pour créer une vibration cinétique sous la lumière naturelle.",
    image: "/projets/pierre-van-huffel/IMG_0797.JPG",
    gallery: [
      "/projets/pierre-van-huffel/IMG_0810.JPG",
      "/projets/pierre-van-huffel/IMG_08201.JPG",
      "/projets/pierre-van-huffel/IMG_08311.jpg",
      "/projets/pierre-van-huffel/IMG_0834.JPG",
      "/projets/pierre-van-huffel/IMG_0846.JPG",
      "/projets/pierre-van-huffel/IMG_0852.JPG",
      "/projets/pierre-van-huffel/1er-etage.jpg",
      "/projets/pierre-van-huffel/2eme-etage.jpg",
      "/projets/pierre-van-huffel/3eme-etage.jpg",
      "/projets/pierre-van-huffel/4eme-etage.jpg",
      "/projets/pierre-van-huffel/Coupe.jpg",
      "/projets/pierre-van-huffel/rez-de-chaussée.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: false,
    color: "#2e2d28",
    displayOrder: 4,
  },
  {
    id: "projet-chaussee-de-wavre",
    title: "Centre Médical Auderghem",
    category: "Architecture d'Intérieur",
    location: "Auderghem, Bruxelles",
    year: "2022",
    description:
      "Réaménagement intérieur complet d'un centre médical pluridisciplinaire à Auderghem. Radiologie, médecine générale, dentisterie, ORL, gynécologie et psychiatrie. Signalétique graphique forte par service, circulations rationalisées, espaces d'attente humanisés.",
    fullDescription:
      "L'intervention pour ce centre médical, situé à l'angle de deux axes animés d'Auderghem, s'est concentrée sur une mission approfondie d'architecture d'intérieur. Le défi a consisté à repenser totalement l'aménagement des espaces d'un bâtiment aux lignes géométriques franches, dont le volume d'origine, sombre et cloisonné, était inadapté à sa nouvelle vocation. L'espace a été entièrement restructuré pour injecter de la lumière naturelle, clarifier les axes de circulation et répondre aux exigences d'une accessibilité universelle au sein d'un programme dense (radiologie, médecine générale, dentisterie, ORL, gynécologie, psychiatrie). La conception intérieure traduit une volonté de concilier la rigueur fonctionnelle du milieu médical avec le confort psychologique des usagers. Afin de faciliter le repérage et d'humaniser les zones d'attente, chaque service est singularisé par des revêtements muraux graphiques soigneusement sélectionnés. L'association de ces motifs à des teintes douces, un mobilier sobre et des matériaux techniques participe à la création d'un environnement de soin serein.",
    image: "/projets/chaussee-de-wavre/0.JPG",
    gallery: [
      "/projets/chaussee-de-wavre/1.JPG",
      "/projets/chaussee-de-wavre/2.JPG",
      "/projets/chaussee-de-wavre/3.JPG",
      "/projets/chaussee-de-wavre/4.JPG",
      "/projets/chaussee-de-wavre/5.JPG",
      "/projets/chaussee-de-wavre/6.JPG",
      "/projets/chaussee-de-wavre/7.JPG",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: false,
    color: "#282e2d",
    displayOrder: 5,
  },
  {
    id: "projet-fayt",
    title: "Maison Unifamiliale — Fayt",
    category: "Construction Neuve",
    location: "Floreffe, Wallonie",
    year: "2022",
    description:
      "Construction neuve d'une maison unifamiliale quatre façades à Floreffe. Composition volumétrique claire articulant un volume principal à toiture deux versants, un garage et une extension latérale. Brique de parement aux teintes chaudes, menuiseries et toiture en zinc gris anthracite.",
    fullDescription:
      "Ce projet de construction neuve d'une maison unifamiliale quatre façades à Floreffe repose sur une composition volumétrique claire qui allie tradition et contemporanéité. Le bâtiment principal, caractérisé par sa toiture à deux versants, est articulé par l'adjonction de volumes à toitures plates abritant les fonctions de service (garage et entrée) et une extension latérale. Cette manipulation des volumes permet une insertion cohérente dans le profil du terrain tout en structurant les différents accès. Le choix des matériaux — une brique de parement aux teintes chaudes contrastée par des menuiseries et éléments de toiture en zinc gris anthracite — assure une pérennité esthétique et une intégration sobre dans le paysage bâti local. L'organisation spatiale intérieure a été rigoureusement conçue pour répondre à une logique de fluidité et de séparation des fonctions privées et sociales. Au rez-de-chaussée, les espaces de vie sont entièrement tournés vers l'extérieur par de larges baies vitrées, créant un lien direct entre l'intérieur et le jardin tout en optimisant les apports solaires.",
    image: "/projets/fayt/0.png",
    gallery: [
      "/projets/fayt/1.png",
      "/projets/fayt/2.png",
      "/projets/fayt/coupe-1---rudy-bourgeois.jpg",
      "/projets/fayt/coupe-2---rudy-bourgeois.jpg",
      "/projets/fayt/etage---rudy-bourgeois.jpg",
      "/projets/fayt/facade-av---rudy-bourgeois.jpg",
      "/projets/fayt/facade-ar---rudy-bourgeois.jpg",
      "/projets/fayt/facade-l-droite---rudy-bourgeois.jpg",
      "/projets/fayt/facade-l-gauche---rudy-bourgeois.jpg",
      "/projets/fayt/implantation----rudy-bourgeois.jpg",
      "/projets/fayt/rdc---rudy-bourgeois.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: false,
    color: "#2e2a28",
    displayOrder: 6,
  },
  {
    id: "projet-patrice-lumumba",
    title: "Maison Mitoyenne — Tamines",
    category: "Construction Neuve",
    location: "Tamines, Wallonie",
    year: "2022",
    description:
      "Maison unifamiliale trois façades en lisière d'un quartier pavillonnaire à Tamines. Volumétrie archétypale couronnée d'une toiture à deux versants. Parement brique beige clair rythmé par un accent vertical en brique anthracite à l'entrée. Terrasse bois et carport intégré.",
    fullDescription:
      "Située en lisière d'un quartier pavillonnaire verdoyant, cette maison unifamiliale à trois façades s'implante avec justesse sur une parcelle vierge. Le parti pris architectural repose sur une volumétrie archétypale et épurée, couronnée par une toiture à deux versants. Un carport latéral s'articule de manière fluide au volume principal, offrant un abri discret qui prolonge l'alignement de la façade sans en altérer la lecture globale. Le projet profite de son orientation pour générer une relation bidirectionnelle au jardin, créant ainsi des connexions visuelles fortes tant depuis le séjour au rez-de-chaussée que depuis les pièces de nuit à l'étage. L'organisation spatiale se caractérise par des transitions douces entre l'habitat et la nature, notamment grâce à une large terrasse en bois qui prolonge les espaces de vie vers l'extérieur. Le traitement de l'enveloppe extérieure s'appuie sur un jeu de contrastes maîtrisés : le parement principal en brique beige clair est rythmé par une composition verticale en brique anthracite qui souligne et hiérarchise l'entrée principale.",
    image: "/projets/patrice-lumumba/1.png",
    gallery: [
      "/projets/patrice-lumumba/2.png",
      "/projets/patrice-lumumba/3.png",
      "/projets/patrice-lumumba/4.png",
      "/projets/patrice-lumumba/pu--coupe.jpg",
      "/projets/patrice-lumumba/pu--coupe2.jpg",
      "/projets/patrice-lumumba/pu--etage.jpg",
      "/projets/patrice-lumumba/pu--implantation.jpg",
      "/projets/patrice-lumumba/pu--rez-de-chaussée.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: false,
    color: "#2a2828",
    displayOrder: 7,
  },
  {
    id: "projet-raymond-noel",
    title: "Bâtiment Mixte — Bois de Villers",
    category: "Architecture Tertiaire",
    location: "Bois de Villers, Wallonie",
    year: "2023",
    description:
      "Bâtiment administratif et logistique en zone industrielle à Bois de Villers. Le nouveau volume en brique rouge nuancée contraste avec la nef industrielle existante et affirme l'identité de l'entreprise. Garages au rez-de-chaussée, bureaux en plateau aux étages avec larges fenêtres en bandeau.",
    fullDescription:
      "Situé au cœur d'un zoning industriel belge, ce projet consiste en l'édification d'un nouveau volume administratif et logistique attenant à un entrepôt existant. L'intervention architecturale vise à affirmer l'identité de l'entreprise tout en répondant à des impératifs opérationnels stricts. Le projet s'articule autour d'une volumétrie franche, assumant le contraste entre la nef industrielle utilitaire existante et le nouvel édifice revêtu d'une brique rouge nuancée. Ce choix matériel confère au pôle administratif une échelle plus humaine, une lisibilité claire depuis l'espace public et une pérennité esthétique qui revalorise le contexte périurbain et industriel. L'organisation spatiale repose sur une stratification des usages afin d'optimiser la cohabitation des différents travailleurs. Le rez-de-chaussée est entièrement dévolu aux flux lourds et à l'opérationnel, intégrant une série de garages en connexion directe avec les vastes aires de manœuvre. Les étages accueillent les bureaux administratifs bénéficiant de larges fenêtres en bandeau qui maximisent l'apport en lumière naturelle.",
    image: "/projets/raymond-noel/0.png",
    gallery: [
      "/projets/raymond-noel/1.png",
      "/projets/raymond-noel/2.png",
      "/projets/raymond-noel/3.png",
      "/projets/raymond-noel/2eme-etage---dubois.jpg",
      "/projets/raymond-noel/coupe-1---dubois.jpg",
      "/projets/raymond-noel/coupe-2---dubois.jpg",
      "/projets/raymond-noel/façade-avant----dubois.jpg",
      "/projets/raymond-noel/façade-arriere----dubois.jpg",
      "/projets/raymond-noel/façade-laterale-droite----dubois.jpg",
      "/projets/raymond-noel/façade-laterale-gauche----dubois.jpg",
      "/projets/raymond-noel/implantation---dubois.jpg",
      "/projets/raymond-noel/rdc---dubois.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: false,
    color: "#2e2a2a",
    displayOrder: 8,
  },
  {
    id: "projet-halleweg",
    title: "Rénovation & Surélévation — Halleweg",
    category: "Rénovation & Extension",
    location: "Flandre",
    year: "2024",
    description:
      "Rénovation et surélévation d'une maison en bordure de campagne flamande. Extension volumétrique à l'étage abritant la suite parentale orientée vers l'horizon agricole. Enduit clair, menuiseries sombres, terrasse en surplomb à l'avant, connexion de plain-pied au jardin à l'arrière.",
    fullDescription:
      "Située en bordure d'un environnement dégagé typique de la campagne flamande, cette rénovation s'articule autour d'une volonté forte : maximiser la perméabilité visuelle entre les espaces de vie intérieurs et le paysage agricole adjacent. Plutôt que de procéder à une démolition, le parti pris architectural repose sur le maintien et le prolongement de la structure existante par une surélévation ciblée. Cette extension volumétrique à l'étage abrite la suite parentale, pensée comme un volume d'observation privilégié orienté vers l'horizon. L'expression des façades s'appuie sur une matérialité contrastée — l'application d'un enduit extérieur clair associé à des menuiseries sombres — qui redessine la silhouette du bâtiment avec une modernité assumée tout en assurant son intégration dans le site. L'aménagement intérieur et l'organisation des percements ont été dictés par une logique de cadrage architectural : chaque baie vitrée est proportionnée pour intégrer la nature environnante aux espaces du quotidien. À l'avant, le séjour profite de larges ouvertures et se prolonge sur une terrasse en surplomb. À l'arrière, les espaces fonctionnels établissent une connexion directe de plain-pied avec le jardin.",
    image: "/projets/halleweg/0.png",
    gallery: [
      "/projets/halleweg/1.png",
      "/projets/halleweg/coupe--shujaat.jpg",
      "/projets/halleweg/etage--shujaat.jpg",
      "/projets/halleweg/facade-av--shujaat.jpg",
      "/projets/halleweg/facade-ar--shujaat.jpg",
      "/projets/halleweg/facade-l-droite--shujaat.jpg",
      "/projets/halleweg/facade-l-gauche--shujaat.jpg",
      "/projets/halleweg/implantation--shujaat.jpg",
      "/projets/halleweg/rdc--shujaat.jpg",
      "/projets/halleweg/rdj--shujaat.jpg",
    ],
    specs: {
      surface: "N/C",
      duration: "N/C",
      budget: "Confidentiel",
      team: "Premier Art SRL",
    },
    featured: false,
    color: "#2c2e28",
    displayOrder: 9,
  },
];

export const heroSlides = [
  {
    image: "/projets/rue-des-nobles/0.JPG",
    title: "Transformer · Concevoir",
    subtitle: "· Réaliser",
    location: "Premier Art Architecture — Belgique",
  },
  {
    image: "/projets/fayt/1.png",
    title: "Concevoir avec vision.",
    subtitle: "Transformer avec méthode.",
    location: "Projets résidentiels & professionnels",
  },
  {
    image: "/projets/halleweg/Gemini_Generated_Image_ndu0tendu0tendu0.png",
    title: "De l'idée initiale",
    subtitle: "à la réalisation",
    location: "Partout en Belgique",
  },
];

export const services = [
  {
    number: "01",
    title: "Transformation & Rénovation",
    description:
      "Repenser un bâtiment existant pour l'adapter à de nouveaux usages, améliorer son fonctionnement et révéler son potentiel architectural.",
    icon: "building",
  },
  {
    number: "02",
    title: "Extension & Agrandissement",
    description:
      "Créer de nouveaux volumes en continuité avec l'existant, en conciliant esthétique, fonctionnalité et cohérence architecturale.",
    icon: "layers",
  },
  {
    number: "03",
    title: "Construction Neuve",
    description:
      "Concevoir des projets neufs avec une approche contemporaine, rigoureuse et adaptée au contexte architectural, urbain et technique.",
    icon: "home",
  },
  {
    number: "04",
    title: "Réaffectation & Valorisation",
    description:
      "Transformer des lieux existants pour leur donner une nouvelle fonction, optimiser leur usage et créer une valeur durable.",
    icon: "landmark",
  },
];

export const team = [
  {
    name: "Ahmed Chedly ISMAIL",
    role: "Architecte Indépendant",
    description: "Architecte diplômé basé en Belgique, ma pratique est centrée sur la justesse des espaces, la qualité des usages et la maîtrise globale du projet. Fort de plus de huit ans d'expérience sur des projets résidentiels et tertiaires, j'interviens de la première esquisse jusqu'au suivi de chantier.",
    image: "/profil/photo-profil.png",
  },
];

export const stats = [
  { value: "9",    label: "Projets réalisés" },
  { value: "3",    label: "Régions couvertes" },
  { value: "+8",   label: "Ans d'expérience" },
  { value: "100%", label: "Suivi direct" },
];

export const references = [
  { annee: 2025, nom: "Van der Nootstraat 37",       secteur: "Résidentiel",          type: "Rénovation · Extension",              localisation: "Strombeek-Bever",        surface: "190 m²",  statut: "Permis Obtenu" },
  { annee: 2025, nom: "Fayt 11A",                    secteur: "Résidentiel",          type: "Nouvelle Construction",               localisation: "Floreffe",               surface: "250 m²",  statut: "Étude" },
  { annee: 2025, nom: "Rouges Gorges 26",            secteur: "Résidentiel",          type: "Régularisation",                      localisation: "Kraainem",               surface: "340 m²",  statut: "Permis Obtenu" },
  { annee: 2025, nom: "Enghien 10",                  secteur: "Résidentiel",          type: "Nouvelle Construction",               localisation: "Soignies",               surface: "340 m²",  statut: "En cours" },
  { annee: 2025, nom: "Panorama 10",                 secteur: "Résidentiel",          type: "Extension",                           localisation: "Wemmel",                 surface: "300 m²",  statut: "En cours" },
  { annee: 2025, nom: "Vollickstraat 35",            secteur: "Résidentiel",          type: "Extension",                           localisation: "Merchtem",               surface: "616 m²",  statut: "Permis Obtenu" },
  { annee: 2025, nom: "Tournai 324",                 secteur: "Résidentiel",          type: "Régularisation · Rénovation",         localisation: "Ath",                    surface: "260 m²",  statut: "En cours" },
  { annee: 2025, nom: "Gaucheret 201",               secteur: "Résidentiel · Médical",type: "Transformation",                      localisation: "Schaerbeek",             surface: "872 m²",  statut: "En cours" },
  { annee: 2025, nom: "Place Communale 24",          secteur: "Médical",              type: "Régularisation",                      localisation: "Molenbeek",              surface: "470 m²",  statut: "En cours" },
  { annee: 2025, nom: "Ruisbroek 21",                secteur: "Résidentiel",          type: "Régularisation",                      localisation: "Forest",                 surface: "242 m²",  statut: "En cours" },
  { annee: 2025, nom: "Roklijf 35",                  secteur: "Résidentiel",          type: "Extension",                           localisation: "Alost",                  surface: "170 m²",  statut: "Permis Obtenu" },
  { annee: 2024, nom: "Emile Bossaert 27",           secteur: "Médical",              type: "Changement d'affectation",            localisation: "Koekelberg",             surface: "955 m²",  statut: "En cours" },
  { annee: 2024, nom: "Trasserweg 421",              secteur: "Résidentiel",          type: "Extension",                           localisation: "Neder-Over-Heembeek",    surface: "285 m²",  statut: "Permis Obtenu" },
  { annee: 2024, nom: "Tropique 11",                 secteur: "Résidentiel",          type: "Rehausse · Extension",                localisation: "Forest",                 surface: "342 m²",  statut: "Permis Obtenu" },
  { annee: 2024, nom: "Péage 29",                    secteur: "Résidentiel",          type: "Régularisation",                      localisation: "Woluwe-Saint-Lambert",   surface: "185 m²",  statut: "Réalisé" },
  { annee: 2024, nom: "Acaciadreef 2",               secteur: "Résidentiel",          type: "Rehausse",                            localisation: "Dilbeek",                surface: "225 m²",  statut: "En cours" },
  { annee: 2024, nom: "Robert Schumanlaan 6",        secteur: "Résidentiel",          type: "Extension",                           localisation: "Meise",                  surface: "328 m²",  statut: "En cours" },
  { annee: 2024, nom: "Polderstraat 22",             secteur: "Résidentiel",          type: "Extension",                           localisation: "Denderleew",             surface: "305 m²",  statut: "Permis Obtenu" },
  { annee: 2024, nom: "Dental Family",               secteur: "Médical",              type: "Réaménagement",                       localisation: "Charleroi",              surface: "225 m²",  statut: "Réalisé" },
  { annee: 2023, nom: "Chaussée d'Haecht 114–118",  secteur: "Médical",              type: "Régularisation",                      localisation: "Schaerbeek",             surface: "350 m²",  statut: "En cours" },
  { annee: 2023, nom: "Mons 814",                    secteur: "Médical",              type: "Réaménagement",                       localisation: "Anderlecht",             surface: "180 m²",  statut: "Réalisé" },
  { annee: 2023, nom: "Rue Pierre Van Humbeek 53",   secteur: "Résidentiel",          type: "Nouvelle Construction",               localisation: "Molenbeek-Saint-Jean",   surface: "340 m²",  statut: "Réalisé" },
  { annee: 2023, nom: "Wavre 1341",                  secteur: "Médical",              type: "Réaménagement",                       localisation: "Auderghem",              surface: "640 m²",  statut: "Réalisé" },
  { annee: 2022, nom: "Grives 15",                   secteur: "Résidentiel",          type: "Rehausse",                            localisation: "Waterloo",               surface: "189 m²",  statut: "En cours" },
  { annee: 2022, nom: "Patrice Lumumba 7",           secteur: "Résidentiel",          type: "Nouvelle Construction",               localisation: "Tamines",                surface: "120 m²",  statut: "Réalisé" },
  { annee: 2021, nom: "Saint-Denis 379",             secteur: "Résidentiel",          type: "Extension",                           localisation: "Forest",                 surface: "54 m²",   statut: "Permis Obtenu" },
  { annee: 2021, nom: "Emile Vandervelde 64",        secteur: "Résidentiel",          type: "Réaménagement maison 4 façades",      localisation: "Woluwe-Saint-Lambert",   surface: "450 m²",  statut: "Réalisé" },
  { annee: 2021, nom: "Raymond Noël",                secteur: "Industriel",           type: "Extension d'entrepôt",                localisation: "Bois-de-Villers",        surface: "469 m²",  statut: "Permis Obtenu" },
  { annee: 2020, nom: "Halleweg 72",                 secteur: "Résidentiel",          type: "Rénovation · Extension",              localisation: "Beersel",                surface: "255 m²",  statut: "Réalisé" },
  { annee: 2020, nom: "Nobles 5A",                   secteur: "Résidentiel",          type: "Nouvelle Construction",               localisation: "Soye",                   surface: "277 m²",  statut: "Réalisé" },
  { annee: 2020, nom: "Eugène de Smet 33",           secteur: "Résidentiel",          type: "Extension",                           localisation: "Jette",                  surface: "165 m²",  statut: "Réalisé" },
  { annee: 2020, nom: "Sylvain de Nayer 69",         secteur: "Résidentiel",          type: "Extension",                           localisation: "Anderlecht",             surface: "140 m²",  statut: "Réalisé" },
  { annee: 2020, nom: "Place Albert Ier 58",         secteur: "Résidentiel",          type: "Division d'immeuble",                 localisation: "Montignies-sur-Sambre",  surface: "160 m²",  statut: "Permis Obtenu" },
];

export const testimonials = [
  {
    quote: "Premier Art a su transformer notre maison en un espace que nous n'aurions jamais imaginé seuls. Leur écoute et leur précision technique nous ont conquis dès le premier rendez-vous.",
    author: "Sophie & Marc L.",
    project: "Halleweg — Flandre",
  },
  {
    quote: "Une équipe à l'écoute, rigoureuse et créative. Ils ont su comprendre exactement ce que nous cherchions et ont livré bien au-delà de nos attentes.",
    author: "Famille De Smedt",
    project: "Villa Rue des Nobles — Floreffe",
  },
  {
    quote: "De la première esquisse à la remise des clés, Premier Art nous a accompagnés avec professionnalisme et réactivité. Je recommande sans la moindre hésitation.",
    author: "Thomas V.",
    project: "Centre Médical Koekelberg — Bruxelles",
  },
];
